### ISSUE TITLE
Add Dockerhub Credentials to Kubernetes

### ISSUE THREAD

**Issue by mheadd** [cloud-gov/cg-deploy-kubernetes#172]
With the new Dockerhub account obtained, we need to distribute account credentials to any piece of our infrastructure that pulls images from Dockerhub so that rate limiting won't kick in. (Work originally outlined in [this issue](https://github.com/cloud-gov/product/issues/1476)).

**Comment by bengerman13** [comment]
Closing because we're not going to do this before k8s kicks the bucket
